int inc_by_value(int val);
void inc_by_pointer(int* ptr);
void inc_by_reference(int& ref);
void swap(int* X, int* Y);
void swap(int& X, int& Y);
int find_min(int* const arr, int size);
int find_min2(int** const matrix, int rows, int cols);
int my_str_cmp(const char* const s1, const char* const s2);
int day_of_year(int day, int month, int year, int (*nDayTab)[12]);
void day_of_month(int days, int year, int& day, int& month, int (*nDayTab)[12]);
void print_array(int* const arr, int size);
void add_unique(int*& arr, int& size, int value);
int natural_sum(int n);
int encoded32_size(int raw_size);
int decoded32_size(int encode_size);
int encode32(const char* raw_data, int raw_size, char* dst);
int decode32(const char* encoded_data, int encoded_size, char* dst);
void var_args(int first, ...);
int* my_min(int* arr, int size);
